### ISSUE TITLE
Is the Global WAPOR v3 data outside of Africa accessible yet? 

### ISSUE THREAD

**Issue by ecopirate** [un-fao/FAO-Water-Applications#2]
Greetings from Cambodia,

Many thanks for all your efforts:

When I use the WaPORv3_API.pynb Tutorial with no changes I can 
successfully get the example plot map to show using

tif_url = all_rasters[0][1]
bounding_box = [30.0, 30.5, 31.5, 28.5] # left, top, right, bottom
bands = [1]
output_filepath = r"example_subset.tif"

 
However  when I try changing the Bounding Box extent to areas in Cambodia 
the plot map is always blank. No error messages occur.

For example Cambodia Whole Country should be:

bounding_box = [102.0, 15.0, 108.0, 10.0] # left, top, right, bottom

Left = 102 degrees 
Top  = 15 degrees 
Right = 108 degrees
Bottom = 10 degrees

Or An example smaller test area the one degree box around Phnom Penh
would be:

bounding_box = [104.0, 12.0, 105.0, 11.0] # left, top, right, bottom

But so far all plots are blank....

Could I also ask:

1. How do you actually download the clipped Geotiffs once GDAL has produced them?

2.To run the notebook locally, I can run the script to updating the conda yaml config file by running the script on Google colab 
But where is the updated  colab_20230921.yml that I need to download and how to do so?

I obviously have no idea how to download anything from Colab,,,,

Reference:  [Running the notebooks localy](https://github.com/un-fao/FAO-Water-Applications/tree/10a70cda0e0023258bc9152e43a73b6e8e20b669/WaPOR#running-the-notebooks-localy)

**Comment by bertcoerver** [comment]
Hi @ecopirate 

It's probably easiest to use [this Python package to download WaPOR3](https://bitbucket.org/cioapps/wapordl/src/main/) images using Python. Note that indeed not all variables are available in Cambodia, but all the L1's are global.
