### ISSUE TITLE
Access WAPOR _3 data through Rest API via query link does not work

### ISSUE THREAD

**Issue by akshaydr** [un-fao/FAO-Water-Applications#3]
I would like to download Rasters for a specific region via python. The region should be imported as a shape file. 

I am using the following query link [https://data.apps.fao.org/gismgr/api/v2/query/](https://data.apps.fao.org/gismgr/api/v2/query/) 

```
"request_json is of type CropRaster"
query_url = 'https://data.apps.fao.org/gismgr/api/v2/query/'
resp_json = requests.post(query_url, json=request_json, headers=request_headers).json()
```
But this does not work. 

The WAPOR_3 data also does not contain dimensions. 

Are these features still missing or is there a different way to access the data? 

Many Thanks!

**Comment by bertcoerver** [comment]
Hi @akshaydr 

To use Python to download WaPOR3 data, you can either use this [Python package called WaPORDL](https://bitbucket.org/cioapps/wapordl/src/main/) or have a look at this [notebook with instructions on how to call the API from Python](https://github.com/un-fao/FAO-Water-Applications/blob/main/WaPOR/WaPORv3_API.ipynb).

Hope that helps.

**Comment by fhfonsecaa** [comment]
Hi, it seems that neither of the options allows something more flexible like the previous API. 

Like:

- Downloading time series
- Having more coordinates than a bounding box
- Feedback on the state of the request
- Authenticate the user before downloading.

Is any of this somehow implemented or planed to be implemented? I fail to find it in the user manual.
