### ISSUE TITLE
WaPOR_3 Rest API Server Down Bad Gateway 502  

### ISSUE THREAD

**Issue by akshaydr** [un-fao/FAO-Water-Applications#4]
Good Morning,

The WaPOR 3 database seems to be down since yesterday. 

I am getting Bad Gateway 502 error. 

Could you please confirm if this is a server issue? If yes, is there any channels or mailing lists to know when this happens again in the future?

Thank you very much.

Best Regards,
Akshay

**Comment by bertcoerver** [comment]
Hi Akshay,

The API seems to be working for me right now. Can you share your exact request?

Regards,
Bert

**Comment by akshaydr** [comment]
Hi Bert,

Thanks for the response. 

I got an error with `requests.get(url_to_wapor_v3)`.
The error was, `requests.get(url_to_wapor_v3).reason == 'Bad Gateway'` with code `502`.

Best Regards,
Akshay

**Comment by bertcoerver** [comment]
Ok, I'm getting a 200 now with that URL, so I guess the server was temporarily having problems. Feel free to re-open if the problem persists.
